Repository Team-MoMo/MoMo-iOS, pull requests merged in 2021-01, with the labels that each got.

#8 [#7] Color assets 추가
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Resources/Colors.xcassets/Black1.colorset/Contents.json
  MoMo/MoMo/Resources/Colors.xcassets/Black2Nav.colorset/Contents.json
  MoMo/MoMo/Resources/Colors.xcassets/Black3List.colorset/Contents.json
  MoMo/MoMo/Resources/Colors.xcassets/Black4.colorset/Contents.json
  MoMo/MoMo/Resources/Colors.xcassets/Black5Publish.colorset/Contents.json
  MoMo/MoMo/Resources/Colors.xcassets/Black6.colorset/Contents.json
  MoMo/MoMo/Resources/Colors.xcassets/Blue1.colorset/Contents.json
  MoMo/MoMo/Resources/Colors.xcassets/Blue2.colorset/Contents.json
  MoMo/MoMo/Resources/Colors.xcassets/Blue3.colorset/Contents.json
  MoMo/MoMo/Resources/Colors.xcassets/Blue4.colorset/Contents.json
  MoMo/MoMo/Resources/Colors.xcassets/Blue5.colorset/Contents.json
  MoMo/MoMo/Resources/Colors.xcassets/Blue6.colorset/Contents.json
  MoMo/MoMo/Resources/Colors.xcassets/Blue7.colorset/Contents.json
  MoMo/MoMo/Resources/Colors.xcassets/BlueModalAble.colorset/Contents.json
  MoMo/MoMo/Resources/Colors.xcassets/Contents.json
  MoMo/MoMo/Resources/Colors.xcassets/LineFilterGray.colorset/Contents.json
  MoMo/MoMo/Resources/Colors.xcassets/LineLightGray.colorset/Contents.json
  MoMo/MoMo/Resources/Colors.xcassets/ListBlack.colorset/Contents.json
  MoMo/MoMo/Resources/Colors.xcassets/ListEmotion.colorset/Contents.json
  MoMo/MoMo/Resources/Colors.xcassets/ListLightBlack.colorset/Contents.json
  MoMo/MoMo/Resources/Colors.xcassets/ListSubGray.colorset/Contents.json
  MoMo/MoMo/Resources/Colors.xcassets/NavWhite.colorset/Contents.json
  MoMo/MoMo/Resources/Colors.xcassets/TitleNavy.colorset/Contents.json
  MoMo/MoMo/Sources/Extensions/UIColor+Extension.swift
Labels: enhancement

#11 [#10] README 1차 작성
  README.md
Labels: docs

#12 [docs] README markdown 수정
  README.md
Labels: docs

#22 [#21] cocoapods 추가
  .gitignore
Labels: chore

#26 [#24] Constants 파일 수정
  MoMo/MoMo/Resources/Constants/AppConstants.swift
Labels: refactor

#32 [#29] Home day night layout
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Resources/Assets.xcassets/btnIcMyBlue.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/btnIcMyBlue.imageset/btnIcMyBlue.png
  MoMo/MoMo/Resources/Assets.xcassets/btnIcMyBlue.imageset/btnIcMyBlue@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/btnIcMyBlue.imageset/btnIcMyBlue@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/homeIcSwipeDown.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/homeIcSwipeDown.imageset/homeIcSwipeDown.png
  MoMo/MoMo/Resources/Assets.xcassets/homeIcSwipeDown.imageset/homeIcSwipeDown@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/homeIcSwipeDown.imageset/homeIcSwipeDown@3x.png
  MoMo/MoMo/Resources/Colors.xcassets/HomeDay1.colorset/Contents.json
  MoMo/MoMo/Resources/Colors.xcassets/HomeDay2.colorset/Contents.json
  MoMo/MoMo/Resources/Constants/AppConstants.swift
  MoMo/MoMo/Resources/Storyboards/Home.storyboard
  MoMo/MoMo/Sources/Extensions/UIColor+Extension.swift
  MoMo/MoMo/Sources/View/HomeDayNightView.swift
  MoMo/MoMo/Sources/View/HomeDayNightView.xib
  MoMo/MoMo/Sources/ViewControllers/HomeViewController.swift
Labels: feat

#35 [#30] Home_Day, Home_Night buttons
  MoMo/MoMo/Resources/Assets.xcassets/btnIcCalender.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/btnIcCalender.imageset/btnIcCalender.png
  MoMo/MoMo/Resources/Assets.xcassets/btnIcCalender.imageset/btnIcCalender@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/btnIcCalender.imageset/btnIcCalender@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/btnIcMy.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/btnIcMy.imageset/btnIcMy.png
  MoMo/MoMo/Resources/Assets.xcassets/btnIcMy.imageset/btnIcMy@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/btnIcMy.imageset/btnIcMy@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/btnIcMyBlue.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/btnIcMyBlue.imageset/btnIcMy.png
  MoMo/MoMo/Resources/Assets.xcassets/btnIcMyBlue.imageset/btnIcMy@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/btnIcMyBlue.imageset/btnIcMy@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/homeBtnList.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/homeBtnList.imageset/homeBtnList.png
  MoMo/MoMo/Resources/Assets.xcassets/homeBtnList.imageset/homeBtnList@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/homeBtnList.imageset/homeBtnList@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/homeBtnTop.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/homeBtnTop.imageset/homeBtnTop.png
  MoMo/MoMo/Resources/Assets.xcassets/homeBtnTop.imageset/homeBtnTop@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/homeBtnTop.imageset/homeBtnTop@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/homeBtnUpload.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/homeBtnUpload.imageset/homeBtnUpload.png
  MoMo/MoMo/Resources/Assets.xcassets/homeBtnUpload.imageset/homeBtnUpload@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/homeBtnUpload.imageset/homeBtnUpload@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/homeIcSwipeUp.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/homeIcSwipeUp.imageset/homeIcSwipeUp.png
  MoMo/MoMo/Resources/Assets.xcassets/homeIcSwipeUp.imageset/homeIcSwipeUp@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/homeIcSwipeUp.imageset/homeIcSwipeUp@3x.png
  MoMo/MoMo/Resources/Storyboards/Home.storyboard
  MoMo/MoMo/Sources/View/HomeDayNightView.swift
  MoMo/MoMo/Sources/View/HomeDayNightView.xib
  MoMo/MoMo/Sources/ViewControllers/HomeViewController.swift
Labels: feat

#46 [#45] 자간, 행간 지정 함수 extension
  MoMo/MoMo/Sources/Extensions/String+Extension.swift
  MoMo/MoMo/Sources/View/HomeDayNightView.swift
Labels: refactor

#51 [#14] DeepViewConroller 구현
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo.xcodeproj/xcshareddata/xcschemes/MoMo.xcscheme
  MoMo/MoMo/Resources/Assets.xcassets/1005M.imageset/1005M.png
  MoMo/MoMo/Resources/Assets.xcassets/1005M.imageset/1005M@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/1005M.imageset/1005M@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/1005M.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/100M.imageset/100M.png
  MoMo/MoMo/Resources/Assets.xcassets/100M.imageset/100M@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/100M.imageset/100M@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/100M.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/2M.imageset/2M.png
  MoMo/MoMo/Resources/Assets.xcassets/2M.imageset/2M@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/2M.imageset/2M@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/2M.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/300M.imageset/300M.png
  MoMo/MoMo/Resources/Assets.xcassets/300M.imageset/300M@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/300M.imageset/300M@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/300M.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/30M.imageset/30M.png
  MoMo/MoMo/Resources/Assets.xcassets/30M.imageset/30M@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/30M.imageset/30M@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/30M.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/700M.imageset/700M.png
  MoMo/MoMo/Resources/Assets.xcassets/700M.imageset/700M@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/700M.imageset/700M@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/700M.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/deepSea.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/deepSea.imageset/invalidName.png
  MoMo/MoMo/Resources/Assets.xcassets/deepSea.imageset/invalidName@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/deepSea.imageset/invalidName@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/icStep.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/icStep.imageset/icStep.png
  MoMo/MoMo/Resources/Assets.xcassets/icStep.imageset/icStep@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/icStep.imageset/icStep@3x.png
  MoMo/MoMo/Resources/Colors.xcassets/Gradient1.colorset/Contents.json
  MoMo/MoMo/Resources/Colors.xcassets/Gradient2.colorset/Contents.json
  MoMo/MoMo/Resources/Colors.xcassets/Gradient3.colorset/Contents.json
  MoMo/MoMo/Resources/Colors.xcassets/Gradient4.colorset/Contents.json
  MoMo/MoMo/Resources/Colors.xcassets/Gradient5.colorset/Contents.json
  MoMo/MoMo/Resources/Colors.xcassets/Gradient6.colorset/Contents.json
  MoMo/MoMo/Resources/Colors.xcassets/Gradient7.colorset/Contents.json
  MoMo/MoMo/Resources/Colors.xcassets/Gradient8.colorset/Contents.json
  MoMo/MoMo/Resources/Constants/AppConstants.swift
  MoMo/MoMo/Resources/Storyboards/Onboarding.storyboard
  MoMo/MoMo/Sources/Extensions/UIColor+Extension.swift
  MoMo/MoMo/Sources/Extensions/UIImage+Extension.swift
  MoMo/MoMo/Sources/Extensions/UISlider+Extension.swift
  MoMo/MoMo/Sources/Extensions/UIView+Extension.swift
  MoMo/MoMo/Sources/View/DeepSliderView.swift
  MoMo/MoMo/Sources/View/DeepSliderView.xib
  MoMo/MoMo/Sources/ViewControllers/DeepViewController.swift
  MoMo/MoMo/Sources/ViewControllers/OnboardingWriteViewController.swift
  MoMo/MoMo/Sources/ViewControllers/SentenceViewController.swift
Labels: feat

#47 [#36] Home scroll view 구현
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Resources/Assets.xcassets/btnBubble72.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/btnBubble72.imageset/btnBubble72.png
  MoMo/MoMo/Resources/Assets.xcassets/btnBubble72.imageset/btnBubble72@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/btnBubble72.imageset/btnBubble72@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/btnBubble80.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/btnBubble80.imageset/btnBubble80.png
  MoMo/MoMo/Resources/Assets.xcassets/btnBubble80.imageset/btnBubble80@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/btnBubble80.imageset/btnBubble80@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/btnBubble90.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/btnBubble90.imageset/btnBubble90.png
  MoMo/MoMo/Resources/Assets.xcassets/btnBubble90.imageset/btnBubble90@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/btnBubble90.imageset/btnBubble90@3x.png
  MoMo/MoMo/Resources/Colors.xcassets/Gradient1.colorset/Contents.json
  MoMo/MoMo/Resources/Colors.xcassets/Gradient2.colorset/Contents.json
  MoMo/MoMo/Resources/Colors.xcassets/Gradient3.colorset/Contents.json
  MoMo/MoMo/Resources/Colors.xcassets/Gradient4.colorset/Contents.json
  MoMo/MoMo/Resources/Colors.xcassets/Gradient5.colorset/Contents.json
  MoMo/MoMo/Resources/Colors.xcassets/Gradient6.colorset/Contents.json
  MoMo/MoMo/Resources/Colors.xcassets/Gradient7.colorset/Contents.json
  MoMo/MoMo/Resources/Constants/AppConstants.swift
  MoMo/MoMo/Resources/Storyboards/Home.storyboard
  MoMo/MoMo/Sources/Cells/BubbleTableViewCell.swift
  MoMo/MoMo/Sources/Cells/BubbleTableViewCell.xib
  MoMo/MoMo/Sources/Extensions/UIColor+Extension.swift
  MoMo/MoMo/Sources/Extensions/UIImage+Extension.swift
  MoMo/MoMo/Sources/Models/BubbleDummyData.swift
  MoMo/MoMo/Sources/View/HomeDayNightView.swift
  MoMo/MoMo/Sources/View/HomeDayNightView.xib
  MoMo/MoMo/Sources/ViewControllers/HomeViewController.swift
Labels: feat

#54 [#44] Upload write
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Resources/Assets.xcassets/btnArrowUpBlack.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/btnArrowUpBlack.imageset/btnArrowUpBlack.png
  MoMo/MoMo/Resources/Assets.xcassets/btnArrowUpBlack.imageset/btnArrowUpBlack@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/btnArrowUpBlack.imageset/btnArrowUpBlack@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/icAngry14White.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/icAngry14White.imageset/icAngry14White.png
  MoMo/MoMo/Resources/Assets.xcassets/icAngry14White.imageset/icAngry14White@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/icAngry14White.imageset/icAngry14White@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/icBored14White.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/icBored14White.imageset/icBored14White.png
  MoMo/MoMo/Resources/Assets.xcassets/icBored14White.imageset/icBored14White@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/icBored14White.imageset/icBored14White@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/icConsole14White.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/icConsole14White.imageset/icConsole14White.png
  MoMo/MoMo/Resources/Assets.xcassets/icConsole14White.imageset/icConsole14White@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/icConsole14White.imageset/icConsole14White@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/icDepthBlack.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/icDepthBlack.imageset/icDepthBlack.png
  MoMo/MoMo/Resources/Assets.xcassets/icDepthBlack.imageset/icDepthBlack@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/icDepthBlack.imageset/icDepthBlack@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/icHappy14White.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/icHappy14White.imageset/icHappy14White.png
  MoMo/MoMo/Resources/Assets.xcassets/icHappy14White.imageset/icHappy14White@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/icHappy14White.imageset/icHappy14White@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/icLove14White.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/icLove14White.imageset/icLove14White.png
  MoMo/MoMo/Resources/Assets.xcassets/icLove14White.imageset/icLove14White@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/icLove14White.imageset/icLove14White@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/icMemory14White.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/icMemory14White.imageset/icMemory14White.png
  MoMo/MoMo/Resources/Assets.xcassets/icMemory14White.imageset/icMemory14White@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/icMemory14White.imageset/icMemory14White@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/icSad14White.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/icSad14White.imageset/icSad14White.png
  MoMo/MoMo/Resources/Assets.xcassets/icSad14White.imageset/icSad14White@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/icSad14White.imageset/icSad14White@3x.png
  MoMo/MoMo/Resources/Constants/AppConstants.swift
  MoMo/MoMo/Resources/Info.plist
  MoMo/MoMo/Resources/Storyboards/DiaryWrite.storyboard
  MoMo/MoMo/Sources/AppDelegate.swift
  MoMo/MoMo/Sources/SceneDelegate.swift
  MoMo/MoMo/Sources/ViewControllers/DIaryWriteViewController.swift
  MoMo/MoMo/Sources/ViewControllers/OnboardingViewController.swift
  MoMo/Podfile
  MoMo/Podfile.lock
Labels: feat

#67 [#NON_ISSUE] 파일 경로 정리
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Sources/Extensions/Date+Extension.swift
  MoMo/Podfile.lock
Labels: chore

#57 [#53] Login 뷰
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Resources/Assets.xcassets/icAppleLogo.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/icAppleLogo.imageset/icAppleLogo.png
  MoMo/MoMo/Resources/Assets.xcassets/icAppleLogo.imageset/icAppleLogo@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/icAppleLogo.imageset/icAppleLogo@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/icKakaoLogo.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/icKakaoLogo.imageset/icKakaoLogo.png
  MoMo/MoMo/Resources/Assets.xcassets/icKakaoLogo.imageset/icKakaoLogo@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/icKakaoLogo.imageset/icKakaoLogo@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/icMomoLogo.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/icMomoLogo.imageset/icMomoLogo.png
  MoMo/MoMo/Resources/Assets.xcassets/icMomoLogo.imageset/icMomoLogo@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/icMomoLogo.imageset/icMomoLogo@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/momoTextLogo.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/momoTextLogo.imageset/momoTextLogo.png
  MoMo/MoMo/Resources/Assets.xcassets/momoTextLogo.imageset/momoTextLogo@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/momoTextLogo.imageset/momoTextLogo@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/objectLoginSeaweedTopBlur.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/objectLoginSeaweedTopBlur.imageset/objectLoginSeaweedTopBlur.png
  MoMo/MoMo/Resources/Assets.xcassets/objectLoginSeaweedTopBlur.imageset/objectLoginSeaweedTopBlur@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/objectLoginSeaweedTopBlur.imageset/objectLoginSeaweedTopBlur@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/objectLoginShiningBlur.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/objectLoginShiningBlur.imageset/objectLoginShiningBlur.png
  MoMo/MoMo/Resources/Assets.xcassets/objectLoginShiningBlur.imageset/objectLoginShiningBlur@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/objectLoginShiningBlur.imageset/objectLoginShiningBlur@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/objectSeaweedBottomBlur.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/objectSeaweedBottomBlur.imageset/objectSeaweedBottomBlur.png
  MoMo/MoMo/Resources/Assets.xcassets/objectSeaweedBottomBlur.imageset/objectSeaweedBottomBlur@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/objectSeaweedBottomBlur.imageset/objectSeaweedBottomBlur@3x.png
  MoMo/MoMo/Resources/Constants/AppConstants.swift
  MoMo/MoMo/Resources/Storyboards/Login.storyboard
  MoMo/MoMo/Sources/ViewControllers/LoginViewController.swift
Labels: feat

#59 [#56] 로그인 - 이메일 로그인 뷰
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Resources/Assets.xcassets/loginEmail.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/loginEmail.imageset/loginEmail.png
  MoMo/MoMo/Resources/Assets.xcassets/loginEmail.imageset/loginEmail@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/loginEmail.imageset/loginEmail@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/loginPassword.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/loginPassword.imageset/loginPassword.png
  MoMo/MoMo/Resources/Assets.xcassets/loginPassword.imageset/loginPassword@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/loginPassword.imageset/loginPassword@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/splashTextLogo.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/splashTextLogo.imageset/splashTextLogo.png
  MoMo/MoMo/Resources/Assets.xcassets/splashTextLogo.imageset/splashTextLogo@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/splashTextLogo.imageset/splashTextLogo@3x.png
  MoMo/MoMo/Resources/Constants/AppConstants.swift
  MoMo/MoMo/Resources/Storyboards/EmailLogin.storyboard
  MoMo/MoMo/Sources/ViewControllers/EmailLoginViewController.swift
Labels: feat

#62 [#58] 회원가입 뷰
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Resources/Assets.xcassets/loginCheckbox.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/loginCheckbox.imageset/loginCheckbox.png
  MoMo/MoMo/Resources/Assets.xcassets/loginCheckbox.imageset/loginCheckbox@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/loginCheckbox.imageset/loginCheckbox@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/loginCheckboxIntermediate.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/loginCheckboxIntermediate.imageset/loginCheckboxIntermediate.png
  MoMo/MoMo/Resources/Assets.xcassets/loginCheckboxIntermediate.imageset/loginCheckboxIntermediate@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/loginCheckboxIntermediate.imageset/loginCheckboxIntermediate@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/textfieldDelete.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/textfieldDelete.imageset/textfieldDelete.png
  MoMo/MoMo/Resources/Assets.xcassets/textfieldDelete.imageset/textfieldDelete@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/textfieldDelete.imageset/textfieldDelete@3x.png
  MoMo/MoMo/Resources/Colors.xcassets/RedError.colorset/Contents.json
  MoMo/MoMo/Resources/Constants/AppConstants.swift
  MoMo/MoMo/Resources/Storyboards/Join.storyboard
  MoMo/MoMo/Sources/Extensions/UIColor+Extension.swift
  MoMo/MoMo/Sources/ViewControllers/JoinViewController.swift
Labels: feat

#68 [#NON_ISSUE] AlamofireImage 삭제, 중복 상수 삭제
  MoMo/MoMo.xcworkspace/contents.xcworkspacedata
  MoMo/MoMo/Sources/Extensions/UIColor+Extension.swift
  MoMo/Pods/AlamofireImage/LICENSE
  MoMo/Pods/AlamofireImage/README.md
  MoMo/Pods/AlamofireImage/Source/AFIError.swift
  MoMo/Pods/AlamofireImage/Source/Image.swift
  MoMo/Pods/AlamofireImage/Source/ImageCache.swift
  MoMo/Pods/AlamofireImage/Source/ImageDownloader.swift
  MoMo/Pods/AlamofireImage/Source/ImageFilter.swift
  MoMo/Pods/AlamofireImage/Source/Request+AlamofireImage.swift
  MoMo/Pods/AlamofireImage/Source/UIButton+AlamofireImage.swift
  MoMo/Pods/AlamofireImage/Source/UIImage+AlamofireImage.swift
  MoMo/Pods/AlamofireImage/Source/UIImageView+AlamofireImage.swift
Labels: chore

#66 [#38] Diary View Controller 구현
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Resources/Assets.xcassets/btnIcCalender18.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/btnIcCalender18.imageset/btnIcCalender18.png
  MoMo/MoMo/Resources/Assets.xcassets/btnIcCalender18.imageset/btnIcCalender18@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/btnIcCalender18.imageset/btnIcCalender18@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/btnIcDelete18.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/btnIcDelete18.imageset/btnIcDelete18.png
  MoMo/MoMo/Resources/Assets.xcassets/btnIcDelete18.imageset/btnIcDelete18@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/btnIcDelete18.imageset/btnIcDelete18@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/btnIcDepth18.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/btnIcDepth18.imageset/btnIcDepth18.png
  MoMo/MoMo/Resources/Assets.xcassets/btnIcDepth18.imageset/btnIcDepth18@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/btnIcDepth18.imageset/btnIcDepth18@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/btnIcEdit18.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/btnIcEdit18.imageset/btnIcEdit18.png
  MoMo/MoMo/Resources/Assets.xcassets/btnIcEdit18.imageset/btnIcEdit18@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/btnIcEdit18.imageset/btnIcEdit18@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/icFeatherWhite.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/icFeatherWhite.imageset/icFeatherWhite.png
  MoMo/MoMo/Resources/Assets.xcassets/icFeatherWhite.imageset/icFeatherWhite@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/icFeatherWhite.imageset/icFeatherWhite@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/icSubtab.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/icSubtab.imageset/icSubtab.png
  MoMo/MoMo/Resources/Assets.xcassets/icSubtab.imageset/icSubtab@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/icSubtab.imageset/icSubtab@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/iosIcDepthWhite.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/iosIcDepthWhite.imageset/iosIcDepthWhite.png
  MoMo/MoMo/Resources/Assets.xcassets/iosIcDepthWhite.imageset/iosIcDepthWhite@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/iosIcDepthWhite.imageset/iosIcDepthWhite@3x.png
  MoMo/MoMo/Resources/Constants/AppConstants.swift
  MoMo/MoMo/Resources/Storyboards/Diary.storyboard
  MoMo/MoMo/Sources/View/DeepSliderView.swift
  MoMo/MoMo/Sources/View/MenuView.swift
  MoMo/MoMo/Sources/View/MenuView.xib
  MoMo/MoMo/Sources/ViewControllers/DeepViewController.swift
  MoMo/MoMo/Sources/ViewControllers/DiaryViewController.swift
Labels: feat

#72 [#61] OnboardingViewController에 Lottie적용하기
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Resources/Storyboards/Onboarding.storyboard
  MoMo/MoMo/Resources/onboarding_wave_ios.json
  MoMo/MoMo/Sources/ViewControllers/OnboardingViewController.swift
  MoMo/Podfile
  MoMo/Podfile.lock
Labels: feat

#71 [#60] AlertModalView 구현
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Resources/Assets.xcassets/modalIcWarning.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/modalIcWarning.imageset/modalIcWarning.png
  MoMo/MoMo/Resources/Assets.xcassets/modalIcWarning.imageset/modalIcWarning@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/modalIcWarning.imageset/modalIcWarning@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/modalImgWave290.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/modalImgWave290.imageset/modalImgWave290.png
  MoMo/MoMo/Resources/Assets.xcassets/modalImgWave290.imageset/modalImgWave290@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/modalImgWave290.imageset/modalImgWave290@3x.png
  MoMo/MoMo/Sources/View/AlertModalView.swift
  MoMo/MoMo/Sources/View/AlertModalView.xib
  MoMo/MoMo/Sources/ViewControllers/DiaryViewController.swift
Labels: feat

#81 [#52] Upload mood
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Resources/Assets.xcassets/btnCloseBlack.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/btnCloseBlack.imageset/btnCloseBlack.png
  MoMo/MoMo/Resources/Assets.xcassets/btnCloseBlack.imageset/btnCloseBlack@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/btnCloseBlack.imageset/btnCloseBlack@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/btnIcCalender16.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/btnIcCalender16.imageset/btnIcCalender16.png
  MoMo/MoMo/Resources/Assets.xcassets/btnIcCalender16.imageset/btnIcCalender16@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/btnIcCalender16.imageset/btnIcCalender16@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/modalImgWave375.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/modalImgWave375.imageset/modalImgWave375.png
  MoMo/MoMo/Resources/Assets.xcassets/modalImgWave375.imageset/modalImgWave375@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/modalImgWave375.imageset/modalImgWave375@3x.png
  MoMo/MoMo/Resources/Constants/AppConstants.swift
  MoMo/MoMo/Resources/Info.plist
  MoMo/MoMo/Resources/Storyboards/Onboarding.storyboard
  MoMo/MoMo/Sources/Extensions/UploadModalPresentationController.swift
  MoMo/MoMo/Sources/ViewControllers/MoodViewController.swift
  MoMo/MoMo/Sources/ViewControllers/UploadModalViewController.swift
  MoMo/MoMo/Sources/ViewControllers/UploadModalViewController.xib
  MoMo/Podfile.lock
Labels: feat, jeongyeob

#82 [#63] Splash View에 Lottie 추가하기
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Resources/Colors.xcassets/BlutSplash.colorset/Contents.json
  MoMo/MoMo/Resources/Info.plist
  MoMo/MoMo/Resources/Storyboards/Base.lproj/LaunchScreen.storyboard
  MoMo/MoMo/Resources/Storyboards/Splash.storyboard
  MoMo/MoMo/Resources/momo_splash.json
  MoMo/MoMo/Sources/AppDelegate.swift
  MoMo/MoMo/Sources/SceneDelegate.swift
  MoMo/MoMo/Sources/ViewControllers/SplashViewController.swift
  MoMo/Podfile.lock
Labels: feat

#83 [#64] Upload sentence merge
  MoMo/MoMo/Resources/Assets.xcassets/ellipse122.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/ellipse122.imageset/ellipse122.png
  MoMo/MoMo/Resources/Assets.xcassets/ellipse122.imageset/ellipse122@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/ellipse122.imageset/ellipse122@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/uploadCircle.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/uploadCircle.imageset/uploadCircle.png
  MoMo/MoMo/Resources/Assets.xcassets/uploadCircle.imageset/uploadCircle@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/uploadCircle.imageset/uploadCircle@3x.png
  MoMo/MoMo/Resources/Constants/AppConstants.swift
  MoMo/MoMo/Resources/Storyboards/Onboarding.storyboard
  MoMo/MoMo/Sources/SceneDelegate.swift
  MoMo/MoMo/Sources/ViewControllers/SentenceViewController.swift
  MoMo/Podfile.lock
Labels: feat

#105 [#79] Server 통신 공통 파일 생성
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Resources/Constants/APIConstants.swift
  MoMo/MoMo/Sources/APIServices/GenericResponse.swift
  MoMo/MoMo/Sources/APIServices/NetworkResult.swift
Labels: feat

#77 [#75] Find password 뷰
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Resources/Constants/AppConstants.swift
  MoMo/MoMo/Resources/Storyboards/FindPassword.storyboard
  MoMo/MoMo/Resources/Storyboards/Join.storyboard
  MoMo/MoMo/Sources/Extensions/UITextField+Extension.swift
  MoMo/MoMo/Sources/ViewControllers/FindPasswordViewController.swift
  MoMo/MoMo/Sources/ViewControllers/JoinViewController.swift
Labels: feat

#99 [#93] 업로드뷰 연결
  MoMo/MoMo/Resources/Assets.xcassets/btnBackBlack.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/btnBackBlack.imageset/btnBackBlack.png
  MoMo/MoMo/Resources/Assets.xcassets/btnBackBlack.imageset/btnBackBlack@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/btnBackBlack.imageset/btnBackBlack@3x.png
  MoMo/MoMo/Resources/Constants/AppConstants.swift
  MoMo/MoMo/Resources/Storyboards/Diary.storyboard
  MoMo/MoMo/Resources/Storyboards/Onboarding.storyboard
  MoMo/MoMo/Sources/SceneDelegate.swift
  MoMo/MoMo/Sources/View/AlertModalView.swift
  MoMo/MoMo/Sources/ViewControllers/DIaryWriteViewController.swift
  MoMo/MoMo/Sources/ViewControllers/DeepViewController.swift
  MoMo/MoMo/Sources/ViewControllers/DiaryViewController.swift
  MoMo/MoMo/Sources/ViewControllers/MoodViewController.swift
  MoMo/MoMo/Sources/ViewControllers/SentenceViewController.swift
  MoMo/MoMo/Sources/ViewControllers/UploadModalViewController.swift
  MoMo/MoMo/Sources/ViewControllers/UploadModalViewController.xib
Labels: feat

#101 [#38] DiaryViewController에 DiaryWriteViewController 연동하기
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Resources/Constants/AppConstants.swift
  MoMo/MoMo/Resources/Storyboards/DiaryWrite.storyboard
  MoMo/MoMo/Sources/SceneDelegate.swift
  MoMo/MoMo/Sources/ViewControllers/DIaryWriteViewController.swift
  MoMo/MoMo/Sources/ViewControllers/DeepViewController.swift
  MoMo/MoMo/Sources/ViewControllers/DiaryViewController.swift
  MoMo/MoMo/Sources/ViewControllers/MoodViewController.swift
Labels: feat

#104 [#97] DiaryViewController에 DatePickerModal 연동하기
  MoMo/MoMo/Sources/SceneDelegate.swift
  MoMo/MoMo/Sources/ViewControllers/DiaryViewController.swift
  MoMo/MoMo/Sources/ViewControllers/UploadModalViewController.swift
  MoMo/MoMo/Sources/ViewControllers/UploadModalViewController.xib
Labels: feat

#108 [#107] 로그인, 회원가입, 이메일 로그인, 비밀번호 찾기 뷰 연결
  MoMo/MoMo/Resources/Storyboards/EmailLogin.storyboard
  MoMo/MoMo/Resources/Storyboards/Login.storyboard
  MoMo/MoMo/Sources/ViewControllers/EmailLoginViewController.swift
  MoMo/MoMo/Sources/ViewControllers/LoginViewController.swift
Labels: feat

#110 [#109] Signup Service
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Sources/APIServices/MessageResponse.swift
  MoMo/MoMo/Sources/APIServices/Users/SignUpService.swift
  MoMo/MoMo/Sources/Models/SignUpData.swift
Labels: feat

#112 [#92] DeepViewController에 해양동물 오브제 붙이기
  MoMo/MoMo/Resources/Assets.xcassets/objectDeepSeaweedBottom.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/objectDeepSeaweedBottom.imageset/objectDeepSeaweedBottom.png
  MoMo/MoMo/Resources/Assets.xcassets/objectDeepSeaweedBottom.imageset/objectDeepSeaweedBottom@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/objectDeepSeaweedBottom.imageset/objectDeepSeaweedBottom@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/objectDeepSeaweedTop.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/objectDeepSeaweedTop.imageset/objectDeepSeaweedTop.png
  MoMo/MoMo/Resources/Assets.xcassets/objectDeepSeaweedTop.imageset/objectDeepSeaweedTop@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/objectDeepSeaweedTop.imageset/objectDeepSeaweedTop@3x.png
  MoMo/MoMo/Resources/Storyboards/Onboarding.storyboard
Labels: feat

#111 [#91] DiaryViewController에 해양동물 오브제 붙이기
  MoMo/MoMo/Resources/Assets.xcassets/1005MShark2.imageset/1005MShark2.png
  MoMo/MoMo/Resources/Assets.xcassets/1005MShark2.imageset/1005MShark2@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/1005MShark2.imageset/1005MShark2@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/1005MShark2.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/100MTurtle3.imageset/100MTurtle3.png
  MoMo/MoMo/Resources/Assets.xcassets/100MTurtle3.imageset/100MTurtle3@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/100MTurtle3.imageset/100MTurtle3@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/100MTurtle3.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/700MWhale2.imageset/700MWhale2.png
  MoMo/MoMo/Resources/Assets.xcassets/700MWhale2.imageset/700MWhale2@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/700MWhale2.imageset/700MWhale2@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/700MWhale2.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/objectDiarySeaweed.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/objectDiarySeaweed.imageset/objectSeaweed.png
  MoMo/MoMo/Resources/Assets.xcassets/objectDiarySeaweed.imageset/objectSeaweed@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/objectDiarySeaweed.imageset/objectSeaweed@3x.png
  MoMo/MoMo/Resources/Storyboards/Diary.storyboard
  MoMo/MoMo/Sources/ViewControllers/DiaryViewController.swift
Labels: feat

#114 [#96] 앱 아이콘 설정
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-1024.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-120.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-121.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-152.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-167.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-180.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-20.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-29.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-40.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-41.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-42.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-58.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-59.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-60.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-76.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-80.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-81.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-87.png
  MoMo/MoMo/Resources/Assets.xcassets/listBtnFilterBlue.imageset/Contents.json
Labels: feat

#122 [#NON_ISSUE] pbxproj conflict 해결
  MoMo/MoMo.xcodeproj/project.pbxproj
Labels: chore

#123 [#NON_ISSUE] Users 폴더 경로 수정
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Sources/ViewControllers/DiaryViewController.swift
Labels: chore

#126 [#124] Signin Service 작성
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Sources/APIServices/Users/SignInService.swift
  MoMo/MoMo/Sources/APIServices/Users/SignUpService.swift
  MoMo/MoMo/Sources/Models/AuthData.swift
Labels: feat

#134 [#131] Sentences service
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Sources/APIServices/Sentences/SentencesService.swift
Labels: feat

#136 [#125] [#127] [#128] DiariesWithIDService에 get, put, delete 매서드 추가
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Sources/APIServices/Diaries/DiariesWithIDService.swift
Labels: feat

#133 [#129], [#130] Password Service 작성
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Resources/Constants/APIConstants.swift
  MoMo/MoMo/Sources/APIServices/Users/PasswordService.swift
  MoMo/MoMo/Sources/Models/PasswordData.swift
Labels: feat

#135 [#132] diaries service 코드와 모델 추가
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Sources/APIServices/Diaries/DiariesService.swift
  MoMo/MoMo/Sources/Models/CreateDiary.swift
Labels: feat

#137 [#NON_ISSUE] MessageResponse 삭제
  MoMo/MoMo/Sources/APIServices/Users/SignUpService.swift
Labels: feat

#140 [#138] 홈 - 업로드, 리스트 뷰 연결
  MoMo/MoMo/Resources/Storyboards/Home.storyboard
  MoMo/MoMo/Sources/ViewControllers/HomeViewController.swift
Labels: feat

#144 [#143] 리스트뷰 다이어리뷰 연결
  MoMo/MoMo/Sources/Cells/ListTableViewCell.swift
  MoMo/MoMo/Sources/Cells/ListTableViewCell.xib
  MoMo/MoMo/Sources/ViewControllers/DiaryViewController.swift
  MoMo/MoMo/Sources/ViewControllers/ListViewController.swift
Labels: feat, jeongyeob

#154 [#80] DiariesService swagger 업데이트 사항 적용
  MoMo/MoMo/Resources/Constants/APIConstants.swift
  MoMo/MoMo/Sources/APIServices/Diaries/DiariesService.swift
  MoMo/MoMo/Sources/Models/Emotion.swift
  MoMo/MoMo/Sources/SceneDelegate.swift
Labels: feat

#151 [#149] DiaryViewController의 AlertModalView rightButtonTouchUp 수정
  MoMo/MoMo/Sources/ViewControllers/DiaryViewController.swift
Labels: fix

#148 [#147] DiaryWriteViewController 에서 완료버튼 클릭시 일기저장후 현재 뷰 pop
  MoMo/MoMo/Sources/ViewControllers/DIaryWriteViewController.swift
Labels: fix

#155 [#80] Date 연동 전 Scroll뷰 통신 완료
  MoMo/MoMo/Sources/Cells/BubbleTableViewCell.swift
  MoMo/MoMo/Sources/ViewControllers/HomeViewController.swift
Labels: feat

#159 [#156] DiariesWithIDService 수정
  MoMo/MoMo/Sources/APIServices/Diaries/DiariesWithIDService.swift
Labels: fix

#160 [#80] Home server 통신
  MoMo/MoMo/Resources/Constants/AppConstants.swift
  MoMo/MoMo/Sources/APIServices/Diaries/DiariesWithIDService.swift
  MoMo/MoMo/Sources/Cells/BubbleTableViewCell.swift
  MoMo/MoMo/Sources/Models/Emotion.swift
  MoMo/MoMo/Sources/View/HomeDayNightView.swift
  MoMo/MoMo/Sources/ViewControllers/HomeViewController.swift
  MoMo/MoMo/Sources/ViewControllers/MoodViewController.swift
Labels: feat

#162 [#161] 로그인 통신
  MoMo/MoMo/Resources/Constants/APIConstants.swift
  MoMo/MoMo/Sources/APIServices/Diaries/DiariesWithIDService.swift
  MoMo/MoMo/Sources/APIServices/GenericResponse.swift
  MoMo/MoMo/Sources/APIServices/Users/SignInService.swift
  MoMo/MoMo/Sources/Cells/BubbleTableViewCell.swift
  MoMo/MoMo/Sources/Models/AuthData.swift
  MoMo/MoMo/Sources/ViewControllers/EmailLoginViewController.swift
  MoMo/MoMo/Sources/ViewControllers/HomeViewController.swift
Labels: feat, fix

#163 [#161] constraint nil 값 오류 해결
  MoMo/MoMo/Sources/ViewControllers/EmailLoginViewController.swift
  MoMo/MoMo/Sources/ViewControllers/HomeViewController.swift
Labels: feat

#165 [#164] 온보딩-홈 뷰 연결
  MoMo/MoMo/Sources/ViewControllers/DeepViewController.swift
  MoMo/MoMo/Sources/ViewControllers/HomeViewController.swift
  MoMo/MoMo/Sources/ViewControllers/LoginViewController.swift
  MoMo/MoMo/Sources/ViewControllers/MoodViewController.swift
  MoMo/MoMo/Sources/ViewControllers/OnboardingViewController.swift
  MoMo/MoMo/Sources/ViewControllers/SentenceViewController.swift
Labels: feat

#170 [#169] 홈 모달 구현
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Resources/Assets.xcassets/iosBtnModalAble.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/iosBtnModalAble.imageset/iosBtnModalAble.png
  MoMo/MoMo/Resources/Assets.xcassets/iosBtnModalAble.imageset/iosBtnModalAble@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/iosBtnModalAble.imageset/iosBtnModalAble@3x.png
  MoMo/MoMo/Sources/APIServices/Diaries/DiariesService.swift
  MoMo/MoMo/Sources/Extensions/HomeModalPresentation.swift
  MoMo/MoMo/Sources/SceneDelegate.swift
  MoMo/MoMo/Sources/ViewControllers/HomeModalViewController.swift
  MoMo/MoMo/Sources/ViewControllers/HomeModalViewController.xib
  MoMo/MoMo/Sources/ViewControllers/ListViewController.swift
Labels: feat

#176 [#175] 홈 버그 잡기
  MoMo/.swiftlint.yml
  MoMo/MoMo/Resources/Storyboards/Home.storyboard
  MoMo/MoMo/Sources/Cells/BubbleTableViewCell.swift
  MoMo/MoMo/Sources/Cells/BubbleTableViewCell.xib
  MoMo/MoMo/Sources/SceneDelegate.swift
  MoMo/MoMo/Sources/ViewControllers/HomeViewController.swift
Labels: fix

#178 [#177] 앱 아이콘 변경
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-1024.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-120.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-121.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-152.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-167.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-180.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-20.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-29.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-40.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-41.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-42.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-58.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-59.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-60.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-76.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-80.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-81.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-87.png
  MoMo/MoMo/Sources/SceneDelegate.swift
Labels: chore

#183 [#180] userId 연동
  MoMo/MoMo/Sources/ViewControllers/DeepViewController.swift
  MoMo/MoMo/Sources/ViewControllers/SentenceViewController.swift
Labels: fix

#182 [#180] [#181] 최종 발표 시나리오를 위한 버그 픽스 + OnboardingSentenceViewController 와 서버 연동하기
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Resources/Storyboards/Onboarding.storyboard
  MoMo/MoMo/Sources/APIServices/Sentences/OnboardingService.swift
  MoMo/MoMo/Sources/AppDelegate.swift
  MoMo/MoMo/Sources/Models/OnboardingSentence.swift
  MoMo/MoMo/Sources/ViewControllers/DeepViewController.swift
  MoMo/MoMo/Sources/ViewControllers/DiaryViewController.swift
  MoMo/MoMo/Sources/ViewControllers/MoodViewController.swift
  MoMo/MoMo/Sources/ViewControllers/OnboardingWriteViewController.swift
  MoMo/MoMo/Sources/ViewControllers/SentenceViewController.swift
  MoMo/MoMo/Sources/ViewControllers/ViewController.swift
Labels: feat, fix

#184 [#180] 다른뷰에서 홈으로 다시 돌아올때 백버튼이 생기는 문제 수정
  MoMo/MoMo/Sources/ViewControllers/DiaryViewController.swift
  MoMo/MoMo/Sources/ViewControllers/HomeViewController.swift
Labels: fix

#185 Write icon
  MoMo/MoMo/Sources/ViewControllers/DIaryWriteViewController.swift
Labels: fix, jeongyeob

#186 [#NON_ISSUE] README
  README.md
Labels: chore

#191 List serv revise
  MoMo/MoMo/Sources/ViewControllers/ListViewController.swift
  MoMo/MoMo/Sources/ViewControllers/MoodViewController.swift
  MoMo/MoMo/Sources/ViewControllers/UploadModalViewController.swift
Labels: fix, jeongyeob

#192 [#180] DiaryViewController에서 서버로 데이터를 받아오고 나서 오브제가 바뀌지 않는 문제 수정
  MoMo/MoMo/Sources/ViewControllers/DiaryViewController.swift
Labels: fix

#193 [#180] HomeViewController와 DiaryViewController 연결, HeaderView 에 오늘작성한…
  MoMo/MoMo/Sources/View/HomeDayNightView.swift
  MoMo/MoMo/Sources/View/HomeDayNightView.xib
  MoMo/MoMo/Sources/ViewControllers/DiaryViewController.swift
  MoMo/MoMo/Sources/ViewControllers/HomeViewController.swift
Labels: feat, fix

#194 [#NON_ISSUE] 앱잼 끝
  MoMo/MoMo/Sources/View/HomeDayNightView.swift
  MoMo/MoMo/Sources/View/HomeDayNightView.xib
  MoMo/MoMo/Sources/ViewControllers/DiaryViewController.swift
  MoMo/MoMo/Sources/ViewControllers/HomeViewController.swift
  MoMo/MoMo/Sources/ViewControllers/ListViewController.swift
  MoMo/MoMo/Sources/ViewControllers/MoodViewController.swift
  MoMo/MoMo/Sources/ViewControllers/UploadModalViewController.swift
Labels: choyi, haeseok, jeongyeob

#195 [#180] SentenceVC에 버튼 버그 수정
  MoMo/MoMo/Sources/ViewControllers/SentenceViewController.swift
Labels: fix

#200 [feat] 희원이를 위한 머지s2
  MoMo/MoMo/Sources/View/HomeDayNightView.swift
  MoMo/MoMo/Sources/ViewControllers/HomeViewController.swift
  MoMo/MoMo/Sources/ViewControllers/SentenceViewController.swift
Labels: feat

#202 [#201] DiaryVC 에 BlurView 수정
  MoMo/MoMo/Resources/Storyboards/Diary.storyboard
Labels: fix

#203 [#180] [#200] [#201] DiaryVC 에 BlurView 수정 HomeVC에 전체보기 버튼 수정
  MoMo/MoMo/Resources/Storyboards/Diary.storyboard
  MoMo/MoMo/Sources/View/HomeDayNightView.swift
  MoMo/MoMo/Sources/ViewControllers/HomeViewController.swift
  MoMo/MoMo/Sources/ViewControllers/SentenceViewController.swift
Labels: fix

#205 [#204] 스타일 가이드 적용, AppModel 생성
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Resources/Storyboards/Onboarding.storyboard
  MoMo/MoMo/Sources/APIModels/AuthData.swift
  MoMo/MoMo/Sources/APIModels/BubbleDummyData.swift
  MoMo/MoMo/Sources/APIModels/CreateDiary.swift
  MoMo/MoMo/Sources/APIModels/Diary.swift
  MoMo/MoMo/Sources/APIModels/DiaryRecent.swift
  MoMo/MoMo/Sources/APIModels/DiaryWithId.swift
  MoMo/MoMo/Sources/APIModels/Emotion.swift
  MoMo/MoMo/Sources/APIModels/OnboardingSentence.swift
  MoMo/MoMo/Sources/APIModels/PasswordData.swift
  MoMo/MoMo/Sources/APIModels/Sentence.swift
  MoMo/MoMo/Sources/AppModels/AppDepth.swift
  MoMo/MoMo/Sources/AppModels/AppDiary.swift
  MoMo/MoMo/Sources/AppModels/AppEmotion.swift
  MoMo/MoMo/Sources/AppModels/AppSentence.swift
  MoMo/MoMo/Sources/Cells/ListTableViewCell.swift
  MoMo/MoMo/Sources/View/AlertModalView.xib
  MoMo/MoMo/Sources/View/DeepSliderView.swift
  MoMo/MoMo/Sources/View/HomeDayNightView.swift
  MoMo/MoMo/Sources/ViewControllers/DIaryWriteViewController.swift
  MoMo/MoMo/Sources/ViewControllers/DeepViewController.swift
  MoMo/MoMo/Sources/ViewControllers/DiaryViewController.swift
  MoMo/MoMo/Sources/ViewControllers/MoodViewController.swift
  MoMo/MoMo/Sources/ViewControllers/OnboardingWriteViewController.swift
  MoMo/MoMo/Sources/ViewControllers/SentenceViewController.swift
Labels: refactor

#207 [#206] 앱 전체에 다크모드 적용
  MoMo/MoMo/Resources/Storyboards/Diary.storyboard
  MoMo/MoMo/Resources/Storyboards/DiaryWrite.storyboard
  MoMo/MoMo/Resources/Storyboards/FindPassword.storyboard
  MoMo/MoMo/Resources/Storyboards/List.storyboard
  MoMo/MoMo/Resources/Storyboards/Login.storyboard
  MoMo/MoMo/Resources/Storyboards/Onboarding.storyboard
  MoMo/MoMo/Resources/Storyboards/Splash.storyboard
  MoMo/MoMo/Sources/Cells/DepthCollectionViewCell.xib
  MoMo/MoMo/Sources/Cells/EmptyTableViewCell.xib
  MoMo/MoMo/Sources/Cells/ListDateTableViewCell.xib
  MoMo/MoMo/Sources/Cells/ListFilterTableViewCell.xib
  MoMo/MoMo/Sources/Cells/ListTableViewCell.xib
  MoMo/MoMo/Sources/ViewControllers/HomeModalViewController.xib
  MoMo/MoMo/Sources/ViewControllers/ListFilterModalViewController.xib
  MoMo/MoMo/Sources/ViewControllers/UploadModalViewController.xib
Labels: feat

#221 [#218] 리스트뷰 리팩토링
  MoMo/MoMo/Sources/ViewControllers/ListFilterModalViewController.swift
  MoMo/MoMo/Sources/ViewControllers/ListViewController.swift
Labels: refactor

#222 [#219] 리스트뷰 셀 리팩토링
  MoMo/MoMo/Sources/Cells/FilterCollectionViewCell.swift
  MoMo/MoMo/Sources/Cells/ListDateTableViewCell.swift
  MoMo/MoMo/Sources/Cells/ListTableViewCell.swift
  MoMo/MoMo/Sources/ViewControllers/ListViewController.swift
Labels: refactor

#229 [fix] pickerView 타이틀 색 추가
  MoMo/MoMo/Sources/ViewControllers/HomeModalViewController.swift
  MoMo/MoMo/Sources/ViewControllers/ListFilterModalViewController.swift
  MoMo/MoMo/Sources/ViewControllers/UploadModalViewController.swift
Labels: fix, jeongyeob

#232 [#230] list modal
  MoMo/MoMo/Sources/Cells/DepthCollectionViewCell.swift
  MoMo/MoMo/Sources/Cells/EmotionCollectionViewCell.swift
  MoMo/MoMo/Sources/Cells/ListTableViewCell.swift
  MoMo/MoMo/Sources/Cells/ListTableViewCell.xib
  MoMo/MoMo/Sources/ViewControllers/ListFilterModalViewController.swift
  MoMo/MoMo/Sources/ViewControllers/ListViewController.swift
  MoMo/MoMo/Sources/ViewControllers/MoodViewController.swift
Labels: jeongyeob, refactor
