Repository Team-MoMo/MoMo-iOS, pull requests merged in 2021-02, with the labels that each got.

#214 [#211] [#213] AppDate 구현, MoodViewController 리팩토링
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Sources/AppModels/AppDate.swift
  MoMo/MoMo/Sources/ViewControllers/DiaryViewController.swift
  MoMo/MoMo/Sources/ViewControllers/HomeViewController.swift
  MoMo/MoMo/Sources/ViewControllers/MoodViewController.swift
  MoMo/MoMo/Sources/ViewControllers/SentenceViewController.swift
  MoMo/MoMo/Sources/ViewControllers/UploadModalViewController.swift
Labels: refactor

#217 [#120] [#168] 자잘한 버그 수정, DiaryViewController에 메뉴 버튼이 2번 클릭해야 눌리는 문제 수정
  MoMo/MoMo/Resources/Colors.xcassets/OnboardingBlue.colorset/Contents.json
  MoMo/MoMo/Resources/Storyboards/Diary.storyboard
  MoMo/MoMo/Resources/Storyboards/Onboarding.storyboard
  MoMo/MoMo/Sources/SceneDelegate.swift
  MoMo/MoMo/Sources/ViewControllers/DiaryViewController.swift
  MoMo/MoMo/Sources/ViewControllers/SplashViewController.swift
Labels: fix, refactor

#220 [#102] DiaryViewController에서 MenuModalView 오토레이아웃 적용
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Resources/Constants/AppConstants.swift
  MoMo/MoMo/Sources/View/AlertModalView.swift
  MoMo/MoMo/Sources/View/MenuView.swift
  MoMo/MoMo/Sources/View/MenuView.xib
  MoMo/MoMo/Sources/ViewControllers/DIaryWriteViewController.swift
  MoMo/MoMo/Sources/ViewControllers/DiaryViewController.swift
Labels: fix

#225 [#216] DiaryViewController 리팩토링
  MoMo/MoMo/Resources/Storyboards/Diary.storyboard
  MoMo/MoMo/Sources/AppModels/AppDiary.swift
  MoMo/MoMo/Sources/ViewControllers/DIaryWriteViewController.swift
  MoMo/MoMo/Sources/ViewControllers/DeepViewController.swift
  MoMo/MoMo/Sources/ViewControllers/DiaryViewController.swift
Labels: refactor

#234 [#216] [#224] [#233] DiaryViewController, DeepViewController, DiaryWriteViewController 리팩토링
  MoMo/MoMo/Sources/ViewControllers/DIaryWriteViewController.swift
  MoMo/MoMo/Sources/ViewControllers/DeepViewController.swift
  MoMo/MoMo/Sources/ViewControllers/DiaryViewController.swift
Labels: refactor

#235 [#NON_ISSUE] 중괄호 오타 수정
  MoMo/MoMo/Sources/ViewControllers/DIaryWriteViewController.swift
Labels: fix

#243 [#241] SentenceViewConroller 리팩토링
  MoMo/MoMo/Sources/ViewControllers/DIaryWriteViewController.swift
  MoMo/MoMo/Sources/ViewControllers/DeepViewController.swift
  MoMo/MoMo/Sources/ViewControllers/SentenceViewController.swift
Labels: refactor

#244 [#242] OnboardingViewController, OnboardingWriteViewController 리팩토링
  MoMo/MoMo/Sources/ViewControllers/OnboardingViewController.swift
  MoMo/MoMo/Sources/ViewControllers/OnboardingWriteViewController.swift
Labels: refactor

#245 [#215] ToastView 구현
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Sources/View/ToastView.swift
  MoMo/MoMo/Sources/View/ToastView.xib
  MoMo/MoMo/Sources/ViewControllers/DIaryWriteViewController.swift
  MoMo/MoMo/Sources/ViewControllers/DiaryViewController.swift
Labels: feat

#254 [#253] SentenceViewController 에서 네트워크 통신이 안되는 버그 수정
  MoMo/MoMo/Sources/APIModels/Sentence.swift
  MoMo/MoMo/Sources/APIServices/Sentences/SentencesService.swift
  MoMo/MoMo/Sources/ViewControllers/HomeViewController.swift
Labels: fix

#256 [#227] 통계뷰 구현
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Resources/Assets.xcassets/graph1005M.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/graph1005M.imageset/graph1005M.png
  MoMo/MoMo/Resources/Assets.xcassets/graph1005M.imageset/graph1005M@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/graph1005M.imageset/graph1005M@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/graph100M.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/graph100M.imageset/graph100M.png
  MoMo/MoMo/Resources/Assets.xcassets/graph100M.imageset/graph100M@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/graph100M.imageset/graph100M@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/graph2M.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/graph2M.imageset/graph2M.png
  MoMo/MoMo/Resources/Assets.xcassets/graph2M.imageset/graph2M@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/graph2M.imageset/graph2M@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/graph300M.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/graph300M.imageset/graph300M.png
  MoMo/MoMo/Resources/Assets.xcassets/graph300M.imageset/graph300M@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/graph300M.imageset/graph300M@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/graph30M.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/graph30M.imageset/graph30M.png
  MoMo/MoMo/Resources/Assets.xcassets/graph30M.imageset/graph30M@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/graph30M.imageset/graph30M@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/graph700M.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/graph700M.imageset/graph700M.png
  MoMo/MoMo/Resources/Assets.xcassets/graph700M.imageset/graph700M@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/graph700M.imageset/graph700M@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/graphUnder.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/graphUnder.imageset/graphUnder.png
  MoMo/MoMo/Resources/Assets.xcassets/graphUnder.imageset/graphUnder@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/graphUnder.imageset/graphUnder@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/imgGraphBottom.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/imgGraphBottom.imageset/imgGraphBottom.png
  MoMo/MoMo/Resources/Assets.xcassets/imgGraphBottom.imageset/imgGraphBottom@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/imgGraphBottom.imageset/imgGraphBottom@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/imgGraphBottomBoat.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/imgGraphBottomBoat.imageset/imgGraphBottomBoat.png
  MoMo/MoMo/Resources/Assets.xcassets/imgGraphBottomBoat.imageset/imgGraphBottomBoat@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/imgGraphBottomBoat.imageset/imgGraphBottomBoat@3x.png
  MoMo/MoMo/Resources/Constants/AppConstants.swift
  MoMo/MoMo/Resources/Storyboards/Statistics.storyboard
  MoMo/MoMo/Sources/APIModels/DepthCount.swift
  MoMo/MoMo/Sources/APIModels/EmotionCount.swift
  MoMo/MoMo/Sources/APIModels/Statistics.swift
  MoMo/MoMo/Sources/APIServices/Diaries/DiariesStatistics.swift
  MoMo/MoMo/Sources/Extensions/HomeModalPresentation.swift
  MoMo/MoMo/Sources/ViewControllers/DepthStatViewController.swift
  MoMo/MoMo/Sources/ViewControllers/HomeModalViewController.swift
  MoMo/MoMo/Sources/ViewControllers/HomeModalViewController.xib
  MoMo/MoMo/Sources/ViewControllers/ListViewController.swift
  MoMo/MoMo/Sources/ViewControllers/MoodStatViewController.swift
  MoMo/MoMo/Sources/ViewControllers/StatisticsViewController.swift
Labels: feat

#248 [#246] Apple login
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/MoMo.entitlements
  MoMo/MoMo/Resources/Storyboards/Login.storyboard
  MoMo/MoMo/Sources/ViewControllers/LoginViewController.swift
Labels: feat

#258 [#257] 개인정보 이용약관 뷰 구현
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Resources/Constants/AppConstants.swift
  MoMo/MoMo/Resources/Storyboards/PersonalTerm.storyboard
  MoMo/MoMo/Sources/ViewControllers/PersonalTermViewController.swift
  MoMo/MoMo/Sources/ViewControllers/SettingViewController.swift
Labels: feat

#260 [#259] 오픈 소스 뷰와 상세 정보 구현
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Resources/Assets.xcassets/btnArrowRight14.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/btnArrowRight14.imageset/btnArrowRight14.png
  MoMo/MoMo/Resources/Assets.xcassets/btnArrowRight14.imageset/btnArrowRight14@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/btnArrowRight14.imageset/btnArrowRight14@3x.png
  MoMo/MoMo/Resources/Constants/AppConstants.swift
  MoMo/MoMo/Resources/Storyboards/OpenSource.storyboard
  MoMo/MoMo/Sources/Cells/OpenSourceTableViewCell.swift
  MoMo/MoMo/Sources/Cells/OpenSourceTableViewCell.xib
  MoMo/MoMo/Sources/ViewControllers/OpenSourceDetailViewController.swift
  MoMo/MoMo/Sources/ViewControllers/OpenSourceViewController.swift
  MoMo/MoMo/Sources/ViewControllers/SettingViewController.swift
Labels: feat

#270 [#239] LockViewController 구현하기
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Resources/Assets.xcassets/btnLockBack.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/btnLockBack.imageset/btnLockBack.png
  MoMo/MoMo/Resources/Assets.xcassets/btnLockBack.imageset/btnLockBack@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/btnLockBack.imageset/btnLockBack@3x.png
  MoMo/MoMo/Resources/Colors.xcassets/AlertRightButtonGray.colorset/Contents.json
  MoMo/MoMo/Resources/Constants/AppConstants.swift
  MoMo/MoMo/Resources/Storyboards/Lock.storyboard
  MoMo/MoMo/Sources/AppDelegate.swift
  MoMo/MoMo/Sources/Extensions/UIColor+Extension.swift
  MoMo/MoMo/Sources/SceneDelegate.swift
  MoMo/MoMo/Sources/View/AlertModalView.swift
  MoMo/MoMo/Sources/ViewControllers/DIaryWriteViewController.swift
  MoMo/MoMo/Sources/ViewControllers/DiaryViewController.swift
  MoMo/MoMo/Sources/ViewControllers/LockViewController.swift
  MoMo/MoMo/Sources/ViewControllers/SettingViewController.swift
Labels: feat

#273 [#240] ChangePasswordViewController 구현
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Resources/Constants/APIConstants.swift
  MoMo/MoMo/Resources/Constants/AppConstants.swift
  MoMo/MoMo/Resources/Storyboards/ChangePassword.storyboard
  MoMo/MoMo/Resources/Storyboards/Login.storyboard
  MoMo/MoMo/Sources/APIModels/PasswordData.swift
  MoMo/MoMo/Sources/APIServices/Users/PasswordService.swift
  MoMo/MoMo/Sources/ViewControllers/ChangePasswordViewController.swift
  MoMo/MoMo/Sources/ViewControllers/SettingViewController.swift
Labels: feat

#274 [#238] MOMO instagram 셀 터치시 모모 인스타그램으로 화면 전환하기 구현
  MoMo/MoMo/Resources/Info.plist
  MoMo/MoMo/Sources/ViewControllers/SettingViewController.swift
Labels: feat

#276 [#271] EmailLoginViewController의 네비게이션 바에 백버튼이 제대로 적용되어 있지 않은 문제 수정
  MoMo/MoMo/Sources/ViewControllers/EmailLoginViewController.swift
  MoMo/MoMo/Sources/ViewControllers/LoginViewController.swift
Labels: fix

#279 [#209] EmailLoginVC 에 로그인 중에 보여줄 인디케이터 구현
  MoMo/MoMo/Sources/ViewControllers/EmailLoginViewController.swift
Labels: feat

#280 [#267] 카카오톡, 애플, 구글로 로그인 할 경우 환경설정 - 내정보 - 비밀번호 변경 메뉴 삭제기능 구현
  MoMo/MoMo/Sources/AppDelegate.swift
  MoMo/MoMo/Sources/SceneDelegate.swift
  MoMo/MoMo/Sources/ViewControllers/EmailLoginViewController.swift
  MoMo/MoMo/Sources/ViewControllers/SettingViewController.swift
Labels: feat

#292 [#237] 피커뷰 전체 수정
  MoMo/MoMo/Resources/Constants/AppConstants.swift
  MoMo/MoMo/Sources/AppModels/AppEmotion.swift
  MoMo/MoMo/Sources/Cells/EmotionCollectionViewCell.swift
  MoMo/MoMo/Sources/ViewControllers/HomeModalViewController.swift
  MoMo/MoMo/Sources/ViewControllers/ListFilterModalViewController.swift
  MoMo/MoMo/Sources/ViewControllers/ListViewController.swift
  MoMo/MoMo/Sources/ViewControllers/MoodViewController.swift
  MoMo/MoMo/Sources/ViewControllers/StatisticsViewController.swift
  MoMo/MoMo/Sources/ViewControllers/UploadModalViewController.swift
Labels: fix

#275 [#268] [#269] DiaryWriteVC 에 ToastView 추가 & 리팩토링
  MoMo/MoMo/Sources/AppModels/AppDiary.swift
  MoMo/MoMo/Sources/ViewControllers/DIaryWriteViewController.swift
  MoMo/MoMo/Sources/ViewControllers/DeepViewController.swift
  MoMo/MoMo/Sources/ViewControllers/DiaryViewController.swift
  MoMo/MoMo/Sources/ViewControllers/SentenceViewController.swift
Labels: feat, refactor

#281 [#265] Password find alert 구현
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Resources/Assets.xcassets/icCount1.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/icCount1.imageset/icCount1.png
  MoMo/MoMo/Resources/Assets.xcassets/icCount1.imageset/icCount1@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/icCount1.imageset/icCount1@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/icCount2.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/icCount2.imageset/icCount2.png
  MoMo/MoMo/Resources/Assets.xcassets/icCount2.imageset/icCount2@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/icCount2.imageset/icCount2@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/icCount3.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/icCount3.imageset/icCount3.png
  MoMo/MoMo/Resources/Assets.xcassets/icCount3.imageset/icCount3@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/icCount3.imageset/icCount3@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/modalIcCheck.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/modalIcCheck.imageset/modalIcCheck.png
  MoMo/MoMo/Resources/Assets.xcassets/modalIcCheck.imageset/modalIcCheck@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/modalIcCheck.imageset/modalIcCheck@3x.png
  MoMo/MoMo/Resources/Constants/AppConstants.swift
  MoMo/MoMo/Resources/Storyboards/FindPassword.storyboard
  MoMo/MoMo/Sources/View/GetPasswordAlertView.swift
  MoMo/MoMo/Sources/View/GetPasswordAlertView.xib
  MoMo/MoMo/Sources/ViewControllers/FindPasswordViewController.swift
Labels: feat

#283 [#266] 비밀번호 찾기 통신 구현 및 에러 예외처리
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Sources/APIModels/TempPassword.swift
  MoMo/MoMo/Sources/APIServices/Users/PasswordService.swift
  MoMo/MoMo/Sources/ViewControllers/FindPasswordViewController.swift
Labels: feat

#288 [#249] apple 로그인 통신
  MoMo/MoMo/Resources/Constants/APIConstants.swift
  MoMo/MoMo/Sources/APIServices/Users/SignInService.swift
  MoMo/MoMo/Sources/ViewControllers/LoginViewController.swift
Labels: feat

#296 [feat] 서비스 약관 뷰 구현
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Resources/Constants/AppConstants.swift
  MoMo/MoMo/Resources/Storyboards/PersonalTerm.storyboard
  MoMo/MoMo/Resources/Storyboards/ServiceTerm.storyboard
  MoMo/MoMo/Sources/ViewControllers/PersonalTermViewController.swift
  MoMo/MoMo/Sources/ViewControllers/ServiceTermViewController.swift
  MoMo/MoMo/Sources/ViewControllers/SettingViewController.swift
Labels: feat

#299 [fix] 현재 날짜에 여러 일기를 작성할 수 있는 문제 해결
  MoMo/MoMo/Sources/ViewControllers/MoodViewController.swift
Labels: fix

#300 [fix] 리스트뷰 필터 모달 수정
  MoMo/MoMo/Sources/AppModels/AppDate.swift
  MoMo/MoMo/Sources/Cells/ListDateTableViewCell.xib
  MoMo/MoMo/Sources/Cells/ListTableViewCell.swift
  MoMo/MoMo/Sources/Cells/ListTableViewCell.xib
  MoMo/MoMo/Sources/ViewControllers/ListFilterModalViewController.swift
  MoMo/MoMo/Sources/ViewControllers/ListViewController.swift
Labels: fix

#278 [#252] SettingViewController의 내 정보 페이지에 회원탈퇴 버튼 구현
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Sources/APIModels/AuthData.swift
  MoMo/MoMo/Sources/APIServices/Users/UserService.swift
  MoMo/MoMo/Sources/Cells/SettingTableViewCell.xib
  MoMo/MoMo/Sources/ViewControllers/SettingViewController.swift
Labels: feat

#301 [#252] 소셜로그인시 비밀번호 변경 셀이 안보이게 수정
  MoMo/MoMo/Sources/ViewControllers/SettingViewController.swift
Labels: fix

#310 [#308] Bubble 터치가 안 되는 문제 해결
  MoMo/MoMo/Sources/Cells/BubbleTableViewCell.swift
  MoMo/MoMo/Sources/Cells/BubbleTableViewCell.xib
Labels: fix

#321 [#318] Auth관련 뷰에서 Back button 수정
  MoMo/MoMo/Sources/ViewControllers/FindPasswordViewController.swift
  MoMo/MoMo/Sources/ViewControllers/JoinViewController.swift
Labels: fix

#329 [#325] Testflight 배포 준비
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-1024.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-120.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-121.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-152.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-167.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-180.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-20.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-29.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-40.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-41.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-42.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-58.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-59.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-60.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-76.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-80.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-81.png
  MoMo/MoMo/Resources/Assets.xcassets/AppIcon.appiconset/Icon-87.png
Labels: chore

#335 [#334] 비밀번호 찾기 뷰 다크모드 배경 설정
  MoMo/MoMo/Resources/Storyboards/ChangePassword.storyboard
Labels: fix

#320 [#306] 비밀번호 찾기 버튼이 눌려도 비밀번호 찾기 뷰로 넘어가지 않는 문제 해결
  MoMo/MoMo/Sources/ViewControllers/EmailLoginViewController.swift
Labels: fix

#316 [#311, #313, #314, #315] Home 뷰 Gradient, Objet 관련 bug fix
  MoMo/MoMo/Resources/Storyboards/Home.storyboard
  MoMo/MoMo/Sources/ViewControllers/HomeViewController.swift
Labels: fix

#322 [#302] EmailLoginView에서 로그인에 실패할 경우 로딩 인디케이터가 계속 보이는 문제해결
  MoMo/MoMo/Sources/ViewControllers/EmailLoginViewController.swift
Labels: fix

#323 [#303] ChangePasswordViewController API 통신에서 401 status 처리완료
  MoMo/MoMo/Sources/APIServices/Users/UserService.swift
Labels: fix

#324 [#312] 홈뷰의 테이블뷰에 가로줄이 생기는 문제 해결
  MoMo/MoMo/Sources/ViewControllers/HomeViewController.swift
Labels: fix

#337 [#336] 로그인 후 서버통신 전 default text들이 보이는 문제 해결
  MoMo/MoMo/Sources/View/HomeDayNightView.swift
Labels: fix

#341 [#250] Home network fail 문제 해결
  MoMo/MoMo/Sources/View/HomeDayNightView.swift
  MoMo/MoMo/Sources/ViewControllers/HomeViewController.swift
Labels: fix

#338 [#NON_ISSUE] DiaryWrite VC 요일 안 나오는 문제 해결
  MoMo/MoMo/Sources/ViewControllers/DIaryWriteViewController.swift
Labels: feat

#339 [#331] UI(색, 블러, 버튼...) 가 자연스럽지 않거나 제플린과 다른 문제
  MoMo/MoMo/Resources/Colors.xcassets/OnboardingBlue.colorset/Contents.json
  MoMo/MoMo/Resources/Storyboards/Base.lproj/LaunchScreen.storyboard
  MoMo/MoMo/Resources/Storyboards/DiaryWrite.storyboard
  MoMo/MoMo/Resources/Storyboards/Onboarding.storyboard
  MoMo/MoMo/Sources/View/MenuView.xib
  MoMo/MoMo/Sources/ViewControllers/DiaryViewController.swift
Labels: fix

#340 [#NON_ISSUE] API print문 & 추가 서비스 이용 약관 라벨 추가
  MoMo/MoMo/Sources/ViewControllers/DeepViewController.swift
  MoMo/MoMo/Sources/ViewControllers/DiaryViewController.swift
  MoMo/MoMo/Sources/ViewControllers/ListViewController.swift
  MoMo/MoMo/Sources/ViewControllers/MoodViewController.swift
  MoMo/MoMo/Sources/ViewControllers/SentenceViewController.swift
  MoMo/MoMo/Sources/ViewControllers/ServiceTermViewController.swift
  MoMo/MoMo/Sources/ViewControllers/SettingViewController.swift
  MoMo/MoMo/Sources/ViewControllers/StatisticsViewController.swift
  MoMo/MoMo/Sources/ViewControllers/UploadModalViewController.swift
Labels: feat

#342 [#NON_ISSUE] 리스트 네비게이션 타이틀 폰트 수정
  MoMo/MoMo/Sources/ViewControllers/ListViewController.swift
Labels: fix

#345 [#NON_ISSUE] 온보딩에 날짜가 최근으로 나오게 수정
  MoMo/MoMo/Sources/ViewControllers/MoodViewController.swift
Labels: fix
