Repository Team-MoMo/MoMo-iOS, pull requests merged in 2021-03, with the labels that each got.

#365 [#364] 온보딩 후 Auth 뷰 진입 시 navi bar가 안 보이는 문제 해결
  MoMo/MoMo/Sources/ViewControllers/EmailLoginViewController.swift
  MoMo/MoMo/Sources/ViewControllers/LoginViewController.swift
Labels: fix

#367 [#NON_ISSUE] 버전, 빌드 설정
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Resources/Info.plist
Labels: chore

#377 [#358] 비밀번호 변경 뷰에서 키보드에 따라 버튼 움직이는 기능 삭제
  MoMo/MoMo/Sources/ViewControllers/ChangePasswordViewController.swift
Labels: fix

#375 [#348] [#353] [#354] [#355] MOMO Beta 1.0.1 피드백 UI 수정사항 반영 & 리팩토링
  MoMo/MoMo/Resources/Assets.xcassets/btnCloseWhite.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/btnCloseWhite.imageset/btnCloseWhite.png
  MoMo/MoMo/Resources/Assets.xcassets/btnCloseWhite.imageset/btnCloseWhite@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/btnCloseWhite.imageset/btnCloseWhite@3x.png
  MoMo/MoMo/Resources/Constants/AppConstants.swift
  MoMo/MoMo/Resources/Storyboards/Diary.storyboard
  MoMo/MoMo/Resources/Storyboards/DiaryWrite.storyboard
  MoMo/MoMo/Resources/Storyboards/Onboarding.storyboard
  MoMo/MoMo/Sources/AppModels/AppDate.swift
  MoMo/MoMo/Sources/Extensions/String+Extension.swift
  MoMo/MoMo/Sources/View/HomeDayNightView.swift
  MoMo/MoMo/Sources/ViewControllers/DIaryWriteViewController.swift
  MoMo/MoMo/Sources/ViewControllers/DeepViewController.swift
  MoMo/MoMo/Sources/ViewControllers/DiaryViewController.swift
  MoMo/MoMo/Sources/ViewControllers/HomeViewController.swift
  MoMo/MoMo/Sources/ViewControllers/ListViewController.swift
  MoMo/MoMo/Sources/ViewControllers/MoodViewController.swift
  MoMo/MoMo/Sources/ViewControllers/OnboardingViewController.swift
  MoMo/MoMo/Sources/ViewControllers/OnboardingWriteViewController.swift
  MoMo/MoMo/Sources/ViewControllers/SentenceViewController.swift
Labels: feat, fix

#383 [#317] APIConstants 업데이트
  MoMo/MoMo/Sources/ViewControllers/LoginViewController.swift
Labels: fix

#363 [#356] Password regex 수정
  MoMo/MoMo/Sources/ViewControllers/JoinViewController.swift
Labels: fix

#385 [#384] 홈 아이콘 업데이트
  MoMo/MoMo/Resources/Assets.xcassets/btnIcCalender.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/btnIcCalender.imageset/btnIcCalender.png
  MoMo/MoMo/Resources/Assets.xcassets/btnIcCalender.imageset/btnIcCalender@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/btnIcCalender.imageset/btnIcCalender@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/btnIcMy.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/btnIcMy.imageset/btnIcMy.png
  MoMo/MoMo/Resources/Assets.xcassets/btnIcMy.imageset/btnIcMy@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/btnIcMy.imageset/btnIcMy@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/btnIcMyBlue.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/btnIcMyBlue.imageset/btnIcMy.png
  MoMo/MoMo/Resources/Assets.xcassets/btnIcMyBlue.imageset/btnIcMy@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/btnIcMyBlue.imageset/btnIcMy@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/btnIcMyBlue.imageset/btnIcMyBlue.png
  MoMo/MoMo/Resources/Assets.xcassets/btnIcMyBlue.imageset/btnIcMyBlue@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/btnIcMyBlue.imageset/btnIcMyBlue@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/homeBtnList.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/homeBtnList.imageset/homeBtnList.png
  MoMo/MoMo/Resources/Assets.xcassets/homeBtnList.imageset/homeBtnList@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/homeBtnList.imageset/homeBtnList@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/homeBtnTop.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/homeBtnTop.imageset/homeBtnTop.png
  MoMo/MoMo/Resources/Assets.xcassets/homeBtnTop.imageset/homeBtnTop@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/homeBtnTop.imageset/homeBtnTop@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/homeBtnUpload.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/homeBtnUpload.imageset/homeBtnUpload.png
  MoMo/MoMo/Resources/Assets.xcassets/homeBtnUpload.imageset/homeBtnUpload@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/homeBtnUpload.imageset/homeBtnUpload@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/homeIcSwipeDown.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/homeIcSwipeDown.imageset/homeIcSwipeDown.png
  MoMo/MoMo/Resources/Assets.xcassets/homeIcSwipeDown.imageset/homeIcSwipeDown@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/homeIcSwipeDown.imageset/homeIcSwipeDown@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/homeIcSwipeUp.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/homeIcSwipeUp.imageset/homeIcSwipeUp.png
  MoMo/MoMo/Resources/Assets.xcassets/homeIcSwipeUp.imageset/homeIcSwipeUp@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/homeIcSwipeUp.imageset/homeIcSwipeUp@3x.png
Labels: chore

#376 [#362] [#373] 암호변경 뷰에서 인디케이터 4개까지 보이게 수정, 작은 화면을 위해 스택뷰 VerticalSpacing에 비율적용
  MoMo/MoMo/Resources/Storyboards/Lock.storyboard
  MoMo/MoMo/Sources/ViewControllers/LockViewController.swift
Labels: feat

#389 [#236] Text spacing 함수 리팩토링
  MoMo/MoMo/Sources/Extensions/String+Extension.swift
  MoMo/MoMo/Sources/View/HomeDayNightView.swift
  MoMo/MoMo/Sources/ViewControllers/HomeViewController.swift
  MoMo/MoMo/Sources/ViewControllers/OnboardingViewController.swift
Labels: refactor

#393 [#236] Auth, Home 뷰 Text spacing 설정
  MoMo/MoMo/Resources/Assets.xcassets/btnArrowRightBlack.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/btnArrowRightBlack.imageset/btnArrowRightBlack.png
  MoMo/MoMo/Resources/Assets.xcassets/btnArrowRightBlack.imageset/btnArrowRightBlack@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/btnArrowRightBlack.imageset/btnArrowRightBlack@3x.png
  MoMo/MoMo/Resources/Storyboards/EmailLogin.storyboard
  MoMo/MoMo/Resources/Storyboards/FindPassword.storyboard
  MoMo/MoMo/Resources/Storyboards/Join.storyboard
  MoMo/MoMo/Resources/Storyboards/Login.storyboard
  MoMo/MoMo/Sources/Cells/BubbleTableViewCell.swift
  MoMo/MoMo/Sources/View/HomeDayNightView.swift
  MoMo/MoMo/Sources/ViewControllers/EmailLoginViewController.swift
  MoMo/MoMo/Sources/ViewControllers/FindPasswordViewController.swift
  MoMo/MoMo/Sources/ViewControllers/JoinViewController.swift
  MoMo/MoMo/Sources/ViewControllers/LoginViewController.swift
Labels: refactor

#392 [#382], [#388] findPassword modal 다크모드 해제, 오픈소스 라이브러리 뷰에 카카오 로그인 관련 추가
  MoMo/MoMo/Sources/View/GetPasswordAlertView.xib
  MoMo/MoMo/Sources/ViewControllers/OpenSourceViewController.swift
Labels: fix

#391 [#346] 6s에서 회원가입뷰가 깨지는 문제 해결
  MoMo/MoMo/Resources/Assets.xcassets/btnArrowRightBlack.imageset/Contents.json
  MoMo/MoMo/Resources/Storyboards/Join.storyboard
  MoMo/MoMo/Sources/ViewControllers/JoinViewController.swift
Labels: fix

#394 [#386] 서버통신이 안될 시 기본 텍스트 가리기
  MoMo/MoMo/Resources/Storyboards/Diary.storyboard
  MoMo/MoMo/Sources/ViewControllers/DiaryViewController.swift
  MoMo/MoMo/Sources/ViewControllers/SentenceViewController.swift
Labels: fix

#366 [#357] Edge pan gesture 추가
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Sources/Extensions/UINavigationControllerDelegate+Extension.swift
  MoMo/MoMo/Sources/ViewControllers/EmailLoginViewController.swift
  MoMo/MoMo/Sources/ViewControllers/HomeViewController.swift
Labels: feat

#395 [#387] MenuView안에 있는 메뉴가 잘 선택되도록 터치 영역 늘리기
  MoMo/MoMo/Sources/View/MenuView.swift
  MoMo/MoMo/Sources/View/MenuView.xib
  MoMo/MoMo/Sources/ViewControllers/DiaryViewController.swift
Labels: feat

#396 [#390] DeepViewController 에서 DepthSelectionButton이 중복 선택되지 않게 수정, Circle Indicator 추가
  MoMo/MoMo/Resources/Storyboards/Onboarding.storyboard
  MoMo/MoMo/Sources/ViewControllers/DeepViewController.swift
Labels: feat, fix

#400 [#400] 통계 라벨 누르면 모달 present & 통계 갯수 라벨 수정
  MoMo/MoMo/Resources/Storyboards/Statistics.storyboard
  MoMo/MoMo/Sources/ViewControllers/StatisticsViewController.swift
Labels: fix

#399 [#347] 모달 cornerRadius 수정
  MoMo/MoMo/Sources/Extensions/HomeModalPresentation.swift
  MoMo/MoMo/Sources/Extensions/ModalPresentationController.swift
  MoMo/MoMo/Sources/Extensions/UploadModalPresentationController.swift
  MoMo/MoMo/Sources/ViewControllers/ListFilterModalViewController.swift
  MoMo/MoMo/Sources/ViewControllers/ListViewController.swift
  MoMo/MoMo/Sources/ViewControllers/UploadModalViewController.swift
Labels: fix

#402 [#401] 오픈소스 텍스트뷰 수정되는 문제 해결
  MoMo/MoMo/Resources/Storyboards/OpenSource.storyboard
Labels: fix

#408 [NON ISSUE] 스위프트 린트 제약사항 추가
  MoMo/.swiftlint.yml
Labels: fix

#411 [#410] Find password alert label dark mode 해제
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Sources/View/GetPasswordAlertView.xib
Labels: fix

#437 [#NON_ISSUE] 버전, 빌드 번호 업데이트
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Resources/Info.plist
Labels: chore

#419 [#397] [NON_ISSUE] MOMO iOS Beta 1.0.2 이슈 수정
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Resources/Assets.xcassets/2M.imageset/2M.png
  MoMo/MoMo/Resources/Assets.xcassets/2M.imageset/2M@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/2M.imageset/2M@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/30M.imageset/30M.png
  MoMo/MoMo/Resources/Assets.xcassets/30M.imageset/30M@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/30M.imageset/30M@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/deepLine.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/deepLine.imageset/deepLine.png
  MoMo/MoMo/Resources/Assets.xcassets/deepLine.imageset/deepLine@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/deepLine.imageset/deepLine@3x.png
  MoMo/MoMo/Resources/Constants/AppConstants.swift
  MoMo/MoMo/Resources/Storyboards/Diary.storyboard
  MoMo/MoMo/Resources/Storyboards/DiaryWrite.storyboard
  MoMo/MoMo/Resources/Storyboards/Onboarding.storyboard
  MoMo/MoMo/Sources/AppModels/AppDepth.swift
  MoMo/MoMo/Sources/Cells/SettingTableViewCell.swift
  MoMo/MoMo/Sources/Extensions/UIView+Extension.swift
  MoMo/MoMo/Sources/View/AlertModalView.swift
  MoMo/MoMo/Sources/View/CustomVisualEffectView.swift
  MoMo/MoMo/Sources/View/DeepSliderView.swift
  MoMo/MoMo/Sources/View/DeepSliderView.xib
  MoMo/MoMo/Sources/View/ToastView.swift
  MoMo/MoMo/Sources/ViewControllers/ChangePasswordViewController.swift
  MoMo/MoMo/Sources/ViewControllers/DIaryWriteViewController.swift
  MoMo/MoMo/Sources/ViewControllers/DeepViewController.swift
  MoMo/MoMo/Sources/ViewControllers/DiaryViewController.swift
  MoMo/MoMo/Sources/ViewControllers/JoinViewController.swift
  MoMo/MoMo/Sources/ViewControllers/ListViewController.swift
  MoMo/MoMo/Sources/ViewControllers/LockViewController.swift
  MoMo/MoMo/Sources/ViewControllers/LoginViewController.swift
  MoMo/MoMo/Sources/ViewControllers/OnboardingWriteViewController.swift
  MoMo/MoMo/Sources/ViewControllers/SentenceViewController.swift
  MoMo/MoMo/Sources/ViewControllers/SettingViewController.swift
Labels: fix

#421 [#420] 팀모모뷰에서 뷰 전환시 네비바 색깔 고정되는 문제 해결
  MoMo/MoMo/Sources/ViewControllers/TeamViewController.swift
Labels: fix

#424 [#422][#423] 날짜 필터시 콜렉션뷰 활성화 되는 문제 & 네비 타이틀에 필터된 날짜 갱신안되는 문제 수정
  MoMo/MoMo/Resources/Storyboards/List.storyboard
  MoMo/MoMo/Sources/ViewControllers/ListViewController.swift
Labels: fix

#426 [#425] 통계뷰 현재 날짜 기준으로 수정 & 스토리보드 수정
  MoMo/MoMo/Resources/Storyboards/Statistics.storyboard
  MoMo/MoMo/Sources/ViewControllers/DepthStatViewController.swift
  MoMo/MoMo/Sources/ViewControllers/ListViewController.swift
  MoMo/MoMo/Sources/ViewControllers/MoodStatViewController.swift
  MoMo/MoMo/Sources/ViewControllers/StatisticsViewController.swift
Labels: fix

#428 [#427][#431] 리스트뷰에서 일기 미리볼 때 개행을 공백으로 치환 & 리스트뷰에서 플러스 버튼을 누르고 무드뷰로 전환됐을 때 모달이 안 뜨는 문제 해결 & 필터 라벨의 길이가 달라졌을 때 cell 간 spacing이 달라지는 문제 수정
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Sources/Cells/EmptyCollectionViewCell.swift
  MoMo/MoMo/Sources/Cells/EmptyCollectionViewCell.xib
  MoMo/MoMo/Sources/Cells/ListFilterTableViewCell.xib
  MoMo/MoMo/Sources/Cells/ListTableViewCell.swift
  MoMo/MoMo/Sources/ViewControllers/ListViewController.swift
Labels: fix

#440 [NON_ISSUE] 중복코드 삭제
  MoMo/MoMo/Sources/ViewControllers/ListViewController.swift
Labels: chore

#449 [#444] 비밀번호 변경시 특수문자가 포함되어 있으면 비밀번호 변경을 하지 못하는 문제 해결
  MoMo/MoMo/Sources/ViewControllers/ChangePasswordViewController.swift
Labels: fix

#448 [#443] 업로드시 DiaryWriteViewController 에서 작가, 책 제목, 출판사, 문장이 제대로 보여지지 않는 문제 해결
  MoMo/MoMo/Sources/ViewControllers/DIaryWriteViewController.swift
Labels: fix

#456 [#NON_ISSUE] 앱스토어 배포 준비
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Resources/Info.plist
  MoMo/MoMo/Resources/Storyboards/EmailLogin.storyboard
  MoMo/MoMo/Sources/Extensions/UINavigationControllerDelegate+Extension.swift
  MoMo/MoMo/Sources/View/HomeDayNightView.xib
  MoMo/MoMo/Sources/ViewControllers/HomeViewController.swift
Labels: chore

#462 [NON_ISSUE] DiaryWrite뷰에서 일기 작성시 텍스트 끝에서만 작성 가능한 문제 수정
  MoMo/MoMo/Sources/ViewControllers/DIaryWriteViewController.swift
Labels: fix

#466 [#464] 암호를 수정하거나 암호를 끄거나 킬때 기존 암호를 검사하고 진행하도록 수정함
  MoMo/MoMo/Sources/ViewControllers/LockViewController.swift
  MoMo/MoMo/Sources/ViewControllers/SettingViewController.swift
Labels: feat

#467 [#463] sceneDidBecomeActive 상태가 되었을때 암호가 걸려있다면 암호 잠금 뷰가 보여지게 함
  MoMo/MoMo/Resources/Constants/AppConstants.swift
  MoMo/MoMo/Sources/AppDelegate.swift
  MoMo/MoMo/Sources/SceneDelegate.swift
  MoMo/MoMo/Sources/ViewControllers/LockViewController.swift
Labels: feat

#468 [#441] MoodViewController에 행간자간 적용
  MoMo/MoMo/Sources/ViewControllers/MoodViewController.swift
Labels: fix

#469 [#458] AlertModalView 의 y좌표를 center로 변경
  MoMo/MoMo/Sources/View/AlertModalView.xib
Labels: fix

#471 [#461] 현재 비밀번호와 새로운 비밀번호가 동일할 경우 에러메세지가 보여지게 수정
  MoMo/MoMo/Resources/Storyboards/ChangePassword.storyboard
  MoMo/MoMo/Sources/ViewControllers/ChangePasswordViewController.swift
  MoMo/MoMo/Sources/ViewControllers/HomeViewController.swift
Labels: feat

#473 [#465] 서버통신 전, 다이어리뷰를 초기화 할 때 initial AppDepth 를 활용하여 배경색과 그라디언트 변경하게 수정
  MoMo/MoMo/Sources/ViewControllers/DeepViewController.swift
  MoMo/MoMo/Sources/ViewControllers/DiaryViewController.swift
  MoMo/MoMo/Sources/ViewControllers/EmailLoginViewController.swift
  MoMo/MoMo/Sources/ViewControllers/HomeViewController.swift
  MoMo/MoMo/Sources/ViewControllers/JoinViewController.swift
  MoMo/MoMo/Sources/ViewControllers/ListViewController.swift
Labels: feat

#476 [#451] DeepViewController 에 쓰이는 300m 와 심해 이미지 교체
  MoMo/MoMo/Resources/Assets.xcassets/300M.imageset/300M.png
  MoMo/MoMo/Resources/Assets.xcassets/300M.imageset/300M@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/300M.imageset/300M@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/deepSea.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/deepSea.imageset/deepSea.png
  MoMo/MoMo/Resources/Assets.xcassets/deepSea.imageset/deepSea@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/deepSea.imageset/deepSea@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/deepSea.imageset/invalidName.png
  MoMo/MoMo/Resources/Assets.xcassets/deepSea.imageset/invalidName@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/deepSea.imageset/invalidName@3x.png
Labels: fix

#480 [#479] nightsea 이미지 재 변경
  MoMo/MoMo/Resources/Assets.xcassets/daySea.imageset/nightSea.png
  MoMo/MoMo/Resources/Assets.xcassets/daySea.imageset/nightSea@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/daySea.imageset/nightSea@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/nightSea.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/nightSea.imageset/nightSea.png
  MoMo/MoMo/Resources/Assets.xcassets/nightSea.imageset/nightSea@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/nightSea.imageset/nightSea@3x.png
  MoMo/MoMo/Resources/Storyboards/ko.lproj/LaunchScreen.strings
  MoMo/MoMo/Resources/Storyboards/ko.lproj/Main.strings
Labels: chore

#481 [#477] Apple로 로그인 아이콘 변경
  MoMo/MoMo/Resources/Storyboards/Login.storyboard
Labels: fix

#482 [#452] 로그인 뷰에서 알림 텍스트가 중앙정렬 되어있지 않은 문제 해결
  MoMo/MoMo/Resources/Assets.xcassets/loginEmail.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/loginEmail.imageset/loginEmail.png
  MoMo/MoMo/Resources/Assets.xcassets/loginEmail.imageset/loginEmail@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/loginEmail.imageset/loginEmail@3x.png
  MoMo/MoMo/Resources/Assets.xcassets/loginPassword.imageset/Contents.json
  MoMo/MoMo/Resources/Assets.xcassets/loginPassword.imageset/loginPassword.png
  MoMo/MoMo/Resources/Assets.xcassets/loginPassword.imageset/loginPassword@2x.png
  MoMo/MoMo/Resources/Assets.xcassets/loginPassword.imageset/loginPassword@3x.png
  MoMo/MoMo/Resources/Storyboards/EmailLogin.storyboard
  MoMo/MoMo/Sources/ViewControllers/EmailLoginViewController.swift
Labels: fix

#488 [#447] 오픈소스 버튼이 아닌 셀 전체 터치시 뷰 전환으로 수정
  MoMo/MoMo/Resources/Storyboards/OpenSource.storyboard
  MoMo/MoMo/Sources/Cells/OpenSourceTableViewCell.xib
  MoMo/MoMo/Sources/ViewControllers/OpenSourceViewController.swift
Labels: fix

#489 [#445] 필터 모달 폰트 수정
  MoMo/MoMo/Sources/ViewControllers/ListFilterModalViewController.xib
Labels: fix

#491 [#490] 무드통계 조건문 수정
  MoMo/MoMo/Sources/ViewControllers/DepthStatViewController.swift
Labels: fix

#485 [#483] 다크모드일 때 status bar 세팅 수정
  MoMo/MoMo/Sources/ViewControllers/DIaryWriteViewController.swift
  MoMo/MoMo/Sources/ViewControllers/ListViewController.swift
  MoMo/MoMo/Sources/ViewControllers/MoodViewController.swift
Labels: fix

#487 [#459] 해당 날에 버튼이 활성화되는 문제 수정
  MoMo/MoMo/Sources/ViewControllers/UploadModalViewController.swift
Labels: fix

#486 [#484] 홈에서 작성 뷰로 전환됐을 때 현재 날짜에 일기가 있으면 모달 present가 안되어 있는 문제
  MoMo/MoMo/Sources/ViewControllers/ListViewController.swift
  MoMo/MoMo/Sources/ViewControllers/MoodViewController.swift
Labels: fix

#493 [#474] 암호가 잠겨있을경우 깊이 뷰에서 블러가 풀리는 문제 해결
  MoMo/MoMo/Sources/ViewControllers/DeepViewController.swift
Labels: fix

#496 [#494, #495] 카카오톡 앱이 깔려있지 않을 때 에러처리, GA 등록
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Resources/GoogleService-Info.plist
  MoMo/MoMo/Sources/AppDelegate.swift
  MoMo/MoMo/Sources/ViewControllers/LoginViewController.swift
  MoMo/Podfile
  MoMo/Podfile.lock
Labels: feat, fix

#498 [#497] team momo 뷰 리젝 해결
  MoMo/MoMo.xcodeproj/project.pbxproj
  MoMo/MoMo/Resources/Storyboards/Team.storyboard
  MoMo/Podfile.lock
Labels: chore
